### ISSUE TITLE
SDL2 Mixer not working

### ISSUE THREAD

**Issue by atsb** [Losilof39/glDoom#8]
The SDL2 Mixer backend seems to create the DOOMSONG midi correctly but is not playing it in-game, only sound fx.

Also, great stuff you have done here, I never really had a lot of time for it and it is nice to see it getting the refresh it deserves!

~Gib

**Comment by Wolf3s** [comment]
> The SDL2 Mixer backend seems to create the DOOMSONG midi correctly but is not playing it in-game, only sound fx.
> 
> Also, great stuff you have done here, I never really had a lot of time for it and it is nice to see it getting the refresh it deserves!
> 
> ~Gib

It needs more work on SDL2_mixer maybe is not reading and writting the file in game

**Comment by atsb** [comment]
I'll take a look then, maybe also do the Sigil and NRFTL additions

**Comment by Wolf3s** [comment]
> I'll take a look then, maybe also do the Sigil and NRFTL additions

Nice, but contribute into my [repo](https://github.com/Doom-modding-and-etc/glDoom/tree/SDL2) or wait my repo to be merged before anything else

**Comment by atsb** [comment]
Sure.  I've pushed my stuff (For Sigil and some other fixes) to my original repo
[here](https://github.com/atsb/glDoom/commit/aa605026cf73f958db2055d3fee0ab77339bb468)

**Comment by Wolf3s** [comment]
> Sure. I've pushed my stuff (For Sigil and some other fixes) to my original repo [here](https://github.com/atsb/glDoom/commit/aa605026cf73f958db2055d3fee0ab77339bb468)

Thanks, also i put your chanes into my test [branch](https://github.com/Doom-modding-and-etc/glDoom/tree/atsb-changes), this feature is unstable to use because it's not listing the episode 5

**Comment by Losilof39** [comment]
> The SDL2 Mixer backend seems to create the DOOMSONG midi correctly but is not playing it in-game, only sound fx.
> 
> Also, great stuff you have done here, I never really had a lot of time for it and it is nice to see it getting the refresh it deserves!
> 
> ~Gib

Thanks mate :). I know I'm a bit late for responding but I'll try fix every bugs on this port
